/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TicketList;
import io.swagger.model.TicketStatusRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-11-04T16:07:00.596Z")

@Api(value = "checkTicketStatus", description = "the checkTicketStatus API")
public interface CheckTicketStatusApi {

    @ApiOperation(value = "Returns the status of a ticket", nickname = "checkTicketStatus", notes = "Multiple status values can be provided with comma separated strings", response = TicketList.class, tags={ "ticket", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Response received.", response = TicketList.class),
        @ApiResponse(code = 405, message = "Invalid request")})
    @RequestMapping(value = "/checkTicketStatus",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<TicketList> checkTicketStatus(@ApiParam(value = "Ticket information" ,required=true )  @Valid @RequestBody TicketStatusRequest body);

}
