/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ApiRequest;
import io.swagger.model.ValidateTicketResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-14T21:38:57.474Z")

@Api(value = "validateTicket", description = "the validateTicket API")
public interface ValidateTicketApi {

    @ApiOperation(value = "Checks to see if ticket is valid", nickname = "validateTicket", notes = "Multiple status values can be provided with comma separated strings", response = ValidateTicketResponse.class, tags={ "ticket", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ticket is valid", response = ValidateTicketResponse.class),
        @ApiResponse(code = 201, message = "Ticket validated successfully", response = ValidateTicketResponse.class),
        @ApiResponse(code = 405, message = "Ticket expired", response = ValidateTicketResponse.class),
        @ApiResponse(code = 400, message = "Invalid request", response = ValidateTicketResponse.class),
        @ApiResponse(code = 404, message = "Invaled ticket", response = ValidateTicketResponse.class)})
    @RequestMapping(value = "/validate",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<ValidateTicketResponse> validateTicket(@ApiParam(value = "Information needed to create a ticket" ,required=true )  @Valid @RequestBody ApiRequest body);

}
